[package]
name = "Treasury"
edition = "2024.beta"
version = "0.0.1"
license = "MIT"

[dependencies]
MessageLibCommon = { local = "../message-lib-common", override = true }
Utils = { local = "../../utils", override = true }

[addresses]
treasury = "0x0"

[dev-dependencies]

[dev-addresses]
