
[package]
name = "OFTPTBBuilder"
version = "0.0.1"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
license = "MIT"       # e.g., "MIT", "GPL", "Apache 2.0"

[dependencies]
OFT = { local = "../oft" }
PtbMoveCall = { local = "../../../ptb-builders/ptb-move-call" }

[addresses]
oft_ptb_builder = "0x0"

[dev-dependencies]

[dev-addresses]
